// export by github.com/goplus/igop/cmd/qexp

package tk

import (
	q "github.com/visualfc/atk/tk"

	"go/constant"
	"reflect"

	"github.com/goplus/igop"
)

func init() {
	igop.RegisterPackage(&igop.Package{
		Name: "tk",
		Path: "github.com/visualfc/atk/tk",
		Deps: map[string]string{
			"errors":                            "errors",
			"fmt":                               "fmt",
			"github.com/visualfc/atk/tk/interp": "interp",
			"image":                             "image",
			"image/color":                       "color",
			"image/png":                         "png",
			"log":                               "log",
			"os":                                "os",
			"path/filepath":                     "filepath",
			"reflect":                           "reflect",
			"runtime":                           "runtime",
			"strconv":                           "strconv",
			"strings":                           "strings",
			"sync":                              "sync",
			"unicode/utf8":                      "utf8",
		},
		Interfaces: map[string]reflect.Type{
			"Font":         reflect.TypeOf((*q.Font)(nil)).Elem(),
			"Layout":       reflect.TypeOf((*q.Layout)(nil)).Elem(),
			"LayoutWidget": reflect.TypeOf((*q.LayoutWidget)(nil)).Elem(),
			"NamedId":      reflect.TypeOf((*q.NamedId)(nil)).Elem(),
			"Theme":        reflect.TypeOf((*q.Theme)(nil)).Elem(),
			"Widget":       reflect.TypeOf((*q.Widget)(nil)).Elem(),
			"WindowWidget": reflect.TypeOf((*q.WindowWidget)(nil)).Elem(),
		},
		NamedTypes: map[string]reflect.Type{
			"Action":         reflect.TypeOf((*q.Action)(nil)).Elem(),
			"ActionGroup":    reflect.TypeOf((*q.ActionGroup)(nil)).Elem(),
			"Anchor":         reflect.TypeOf((*q.Anchor)(nil)).Elem(),
			"BaseFont":       reflect.TypeOf((*q.BaseFont)(nil)).Elem(),
			"BaseWidget":     reflect.TypeOf((*q.BaseWidget)(nil)).Elem(),
			"BorderMode":     reflect.TypeOf((*q.BorderMode)(nil)).Elem(),
			"Button":         reflect.TypeOf((*q.Button)(nil)).Elem(),
			"Canvas":         reflect.TypeOf((*q.Canvas)(nil)).Elem(),
			"CheckButton":    reflect.TypeOf((*q.CheckButton)(nil)).Elem(),
			"ComboBox":       reflect.TypeOf((*q.ComboBox)(nil)).Elem(),
			"Command":        reflect.TypeOf((*q.Command)(nil)).Elem(),
			"CommandEx":      reflect.TypeOf((*q.CommandEx)(nil)).Elem(),
			"Compound":       reflect.TypeOf((*q.Compound)(nil)).Elem(),
			"Direction":      reflect.TypeOf((*q.Direction)(nil)).Elem(),
			"DisplyCursor":   reflect.TypeOf((*q.DisplyCursor)(nil)).Elem(),
			"Entry":          reflect.TypeOf((*q.Entry)(nil)).Elem(),
			"Event":          reflect.TypeOf((*q.Event)(nil)).Elem(),
			"EventAttr":      reflect.TypeOf((*q.EventAttr)(nil)).Elem(),
			"FileType":       reflect.TypeOf((*q.FileType)(nil)).Elem(),
			"Fill":           reflect.TypeOf((*q.Fill)(nil)).Elem(),
			"FontAttr":       reflect.TypeOf((*q.FontAttr)(nil)).Elem(),
			"Frame":          reflect.TypeOf((*q.Frame)(nil)).Elem(),
			"Geometry":       reflect.TypeOf((*q.Geometry)(nil)).Elem(),
			"GridIndexAttr":  reflect.TypeOf((*q.GridIndexAttr)(nil)).Elem(),
			"GridLayout":     reflect.TypeOf((*q.GridLayout)(nil)).Elem(),
			"Image":          reflect.TypeOf((*q.Image)(nil)).Elem(),
			"ImageAttr":      reflect.TypeOf((*q.ImageAttr)(nil)).Elem(),
			"Justify":        reflect.TypeOf((*q.Justify)(nil)).Elem(),
			"KeyEvent":       reflect.TypeOf((*q.KeyEvent)(nil)).Elem(),
			"KeyModifier":    reflect.TypeOf((*q.KeyModifier)(nil)).Elem(),
			"Label":          reflect.TypeOf((*q.Label)(nil)).Elem(),
			"LabelFrame":     reflect.TypeOf((*q.LabelFrame)(nil)).Elem(),
			"LayoutAttr":     reflect.TypeOf((*q.LayoutAttr)(nil)).Elem(),
			"LayoutFrame":    reflect.TypeOf((*q.LayoutFrame)(nil)).Elem(),
			"LayoutItem":     reflect.TypeOf((*q.LayoutItem)(nil)).Elem(),
			"LayoutSpacer":   reflect.TypeOf((*q.LayoutSpacer)(nil)).Elem(),
			"LineWrapMode":   reflect.TypeOf((*q.LineWrapMode)(nil)).Elem(),
			"ListBox":        reflect.TypeOf((*q.ListBox)(nil)).Elem(),
			"ListBoxEx":      reflect.TypeOf((*q.ListBoxEx)(nil)).Elem(),
			"ListSelectMode": reflect.TypeOf((*q.ListSelectMode)(nil)).Elem(),
			"Menu":           reflect.TypeOf((*q.Menu)(nil)).Elem(),
			"MenuButton":     reflect.TypeOf((*q.MenuButton)(nil)).Elem(),
			"MessageBoxIcon": reflect.TypeOf((*q.MessageBoxIcon)(nil)).Elem(),
			"MessageBoxType": reflect.TypeOf((*q.MessageBoxType)(nil)).Elem(),
			"MetaClass":      reflect.TypeOf((*q.MetaClass)(nil)).Elem(),
			"MetaType":       reflect.TypeOf((*q.MetaType)(nil)).Elem(),
			"NativeAttr":     reflect.TypeOf((*q.NativeAttr)(nil)).Elem(),
			"Notebook":       reflect.TypeOf((*q.Notebook)(nil)).Elem(),
			"Orient":         reflect.TypeOf((*q.Orient)(nil)).Elem(),
			"PackLayout":     reflect.TypeOf((*q.PackLayout)(nil)).Elem(),
			"Pad":            reflect.TypeOf((*q.Pad)(nil)).Elem(),
			"Paned":          reflect.TypeOf((*q.Paned)(nil)).Elem(),
			"PlaceFrame":     reflect.TypeOf((*q.PlaceFrame)(nil)).Elem(),
			"Pos":            reflect.TypeOf((*q.Pos)(nil)).Elem(),
			"ProgressBar":    reflect.TypeOf((*q.ProgressBar)(nil)).Elem(),
			"RadioButton":    reflect.TypeOf((*q.RadioButton)(nil)).Elem(),
			"RadioGroup":     reflect.TypeOf((*q.RadioGroup)(nil)).Elem(),
			"ReliefStyle":    reflect.TypeOf((*q.ReliefStyle)(nil)).Elem(),
			"Scale":          reflect.TypeOf((*q.Scale)(nil)).Elem(),
			"ScrollBar":      reflect.TypeOf((*q.ScrollBar)(nil)).Elem(),
			"ScrollLayout":   reflect.TypeOf((*q.ScrollLayout)(nil)).Elem(),
			"Separator":      reflect.TypeOf((*q.Separator)(nil)).Elem(),
			"Side":           reflect.TypeOf((*q.Side)(nil)).Elem(),
			"Size":           reflect.TypeOf((*q.Size)(nil)).Elem(),
			"SpinBox":        reflect.TypeOf((*q.SpinBox)(nil)).Elem(),
			"State":          reflect.TypeOf((*q.State)(nil)).Elem(),
			"Sticky":         reflect.TypeOf((*q.Sticky)(nil)).Elem(),
			"SysFont":        reflect.TypeOf((*q.SysFont)(nil)).Elem(),
			"SysFontType":    reflect.TypeOf((*q.SysFontType)(nil)).Elem(),
			"Text":           reflect.TypeOf((*q.Text)(nil)).Elem(),
			"TextEx":         reflect.TypeOf((*q.TextEx)(nil)).Elem(),
			"TextIndex":      reflect.TypeOf((*q.TextIndex)(nil)).Elem(),
			"TreeItem":       reflect.TypeOf((*q.TreeItem)(nil)).Elem(),
			"TreeSelectMode": reflect.TypeOf((*q.TreeSelectMode)(nil)).Elem(),
			"TreeView":       reflect.TypeOf((*q.TreeView)(nil)).Elem(),
			"TreeViewEx":     reflect.TypeOf((*q.TreeViewEx)(nil)).Elem(),
			"UserFont":       reflect.TypeOf((*q.UserFont)(nil)).Elem(),
			"WidgetAttr":     reflect.TypeOf((*q.WidgetAttr)(nil)).Elem(),
			"WidgetInfo":     reflect.TypeOf((*q.WidgetInfo)(nil)).Elem(),
			"WidgetType":     reflect.TypeOf((*q.WidgetType)(nil)).Elem(),
			"Window":         reflect.TypeOf((*q.Window)(nil)).Elem(),
			"WindowInfo":     reflect.TypeOf((*q.WindowInfo)(nil)).Elem(),
		},
		AliasTypes: map[string]reflect.Type{},
		Vars: map[string]reflect.Value{
			"ErrClosed":               reflect.ValueOf(&q.ErrClosed),
			"ErrExist":                reflect.ValueOf(&q.ErrExist),
			"ErrInvalid":              reflect.ValueOf(&q.ErrInvalid),
			"ErrNotExist":             reflect.ValueOf(&q.ErrNotExist),
			"ErrUnsupport":            reflect.ValueOf(&q.ErrUnsupport),
			"ErrorInvalidWidgetInfo":  reflect.ValueOf(&q.ErrorInvalidWidgetInfo),
			"ErrorNotMatchWidgetInfo": reflect.ValueOf(&q.ErrorNotMatchWidgetInfo),
			"TtkTheme":                reflect.ValueOf(&q.TtkTheme),
		},
		Funcs: map[string]reflect.Value{
			"AddVirtualEventPhysicalEvent":     reflect.ValueOf(q.AddVirtualEventPhysicalEvent),
			"AppendLayoutAttrs":                reflect.ValueOf(q.AppendLayoutAttrs),
			"AppendToClipboard":                reflect.ValueOf(q.AppendToClipboard),
			"Async":                            reflect.ValueOf(q.Async),
			"BindEvent":                        reflect.ValueOf(q.BindEvent),
			"BindInfo":                         reflect.ValueOf(q.BindInfo),
			"BindKeyEventEx":                   reflect.ValueOf(q.BindKeyEventEx),
			"ButtonAttrCompound":               reflect.ValueOf(q.ButtonAttrCompound),
			"ButtonAttrImage":                  reflect.ValueOf(q.ButtonAttrImage),
			"ButtonAttrPadding":                reflect.ValueOf(q.ButtonAttrPadding),
			"ButtonAttrState":                  reflect.ValueOf(q.ButtonAttrState),
			"ButtonAttrTakeFocus":              reflect.ValueOf(q.ButtonAttrTakeFocus),
			"ButtonAttrText":                   reflect.ValueOf(q.ButtonAttrText),
			"ButtonAttrWidth":                  reflect.ValueOf(q.ButtonAttrWidth),
			"CanvasAttrBackground":             reflect.ValueOf(q.CanvasAttrBackground),
			"CanvasAttrBorderWidth":            reflect.ValueOf(q.CanvasAttrBorderWidth),
			"CanvasAttrCloseEnough":            reflect.ValueOf(q.CanvasAttrCloseEnough),
			"CanvasAttrConfine":                reflect.ValueOf(q.CanvasAttrConfine),
			"CanvasAttrHeight":                 reflect.ValueOf(q.CanvasAttrHeight),
			"CanvasAttrHighlightBackground":    reflect.ValueOf(q.CanvasAttrHighlightBackground),
			"CanvasAttrHighlightColor":         reflect.ValueOf(q.CanvasAttrHighlightColor),
			"CanvasAttrHighlightthickness":     reflect.ValueOf(q.CanvasAttrHighlightthickness),
			"CanvasAttrInsertBackground":       reflect.ValueOf(q.CanvasAttrInsertBackground),
			"CanvasAttrInsertBorderWidth":      reflect.ValueOf(q.CanvasAttrInsertBorderWidth),
			"CanvasAttrInsertOffTime":          reflect.ValueOf(q.CanvasAttrInsertOffTime),
			"CanvasAttrInsertOnTime":           reflect.ValueOf(q.CanvasAttrInsertOnTime),
			"CanvasAttrInsertWidth":            reflect.ValueOf(q.CanvasAttrInsertWidth),
			"CanvasAttrReliefStyle":            reflect.ValueOf(q.CanvasAttrReliefStyle),
			"CanvasAttrSelectBackground":       reflect.ValueOf(q.CanvasAttrSelectBackground),
			"CanvasAttrSelectborderwidth":      reflect.ValueOf(q.CanvasAttrSelectborderwidth),
			"CanvasAttrSelectforeground":       reflect.ValueOf(q.CanvasAttrSelectforeground),
			"CanvasAttrState":                  reflect.ValueOf(q.CanvasAttrState),
			"CanvasAttrTakeFocus":              reflect.ValueOf(q.CanvasAttrTakeFocus),
			"CanvasAttrWidth":                  reflect.ValueOf(q.CanvasAttrWidth),
			"CanvasAttrXScrollIncrement":       reflect.ValueOf(q.CanvasAttrXScrollIncrement),
			"CanvasAttrYScrollIncrement":       reflect.ValueOf(q.CanvasAttrYScrollIncrement),
			"CheckButtonAttrCompound":          reflect.ValueOf(q.CheckButtonAttrCompound),
			"CheckButtonAttrImage":             reflect.ValueOf(q.CheckButtonAttrImage),
			"CheckButtonAttrPadding":           reflect.ValueOf(q.CheckButtonAttrPadding),
			"CheckButtonAttrState":             reflect.ValueOf(q.CheckButtonAttrState),
			"CheckButtonAttrTakeFocus":         reflect.ValueOf(q.CheckButtonAttrTakeFocus),
			"CheckButtonAttrText":              reflect.ValueOf(q.CheckButtonAttrText),
			"CheckButtonAttrWidth":             reflect.ValueOf(q.CheckButtonAttrWidth),
			"CheckWidgetInfo":                  reflect.ValueOf(q.CheckWidgetInfo),
			"ChildrenOfWidget":                 reflect.ValueOf(q.ChildrenOfWidget),
			"ChooseColor":                      reflect.ValueOf(q.ChooseColor),
			"ChooseDirectory":                  reflect.ValueOf(q.ChooseDirectory),
			"ClearBindEvent":                   reflect.ValueOf(q.ClearBindEvent),
			"ClearClipboard":                   reflect.ValueOf(q.ClearClipboard),
			"ComboBoxAttrBackground":           reflect.ValueOf(q.ComboBoxAttrBackground),
			"ComboBoxAttrEcho":                 reflect.ValueOf(q.ComboBoxAttrEcho),
			"ComboBoxAttrFont":                 reflect.ValueOf(q.ComboBoxAttrFont),
			"ComboBoxAttrForground":            reflect.ValueOf(q.ComboBoxAttrForground),
			"ComboBoxAttrHeight":               reflect.ValueOf(q.ComboBoxAttrHeight),
			"ComboBoxAttrJustify":              reflect.ValueOf(q.ComboBoxAttrJustify),
			"ComboBoxAttrState":                reflect.ValueOf(q.ComboBoxAttrState),
			"ComboBoxAttrTakeFocus":            reflect.ValueOf(q.ComboBoxAttrTakeFocus),
			"ComboBoxAttrValues":               reflect.ValueOf(q.ComboBoxAttrValues),
			"ComboBoxAttrWidth":                reflect.ValueOf(q.ComboBoxAttrWidth),
			"CreateWidgetInfo":                 reflect.ValueOf(q.CreateWidgetInfo),
			"DestroyWidget":                    reflect.ValueOf(q.DestroyWidget),
			"DumpWidget":                       reflect.ValueOf(q.DumpWidget),
			"DumpWidgetEx":                     reflect.ValueOf(q.DumpWidgetEx),
			"EntryAttrBackground":              reflect.ValueOf(q.EntryAttrBackground),
			"EntryAttrExportSelection":         reflect.ValueOf(q.EntryAttrExportSelection),
			"EntryAttrFont":                    reflect.ValueOf(q.EntryAttrFont),
			"EntryAttrForeground":              reflect.ValueOf(q.EntryAttrForeground),
			"EntryAttrJustify":                 reflect.ValueOf(q.EntryAttrJustify),
			"EntryAttrShow":                    reflect.ValueOf(q.EntryAttrShow),
			"EntryAttrState":                   reflect.ValueOf(q.EntryAttrState),
			"EntryAttrTakeFocus":               reflect.ValueOf(q.EntryAttrTakeFocus),
			"EntryAttrWidth":                   reflect.ValueOf(q.EntryAttrWidth),
			"FindWidget":                       reflect.ValueOf(q.FindWidget),
			"FindWidgetInfo":                   reflect.ValueOf(q.FindWidgetInfo),
			"FocusWidget":                      reflect.ValueOf(q.FocusWidget),
			"FontAttrBold":                     reflect.ValueOf(q.FontAttrBold),
			"FontAttrItalic":                   reflect.ValueOf(q.FontAttrItalic),
			"FontAttrOverstrike":               reflect.ValueOf(q.FontAttrOverstrike),
			"FontAttrUnderline":                reflect.ValueOf(q.FontAttrUnderline),
			"FontFamilieList":                  reflect.ValueOf(q.FontFamilieList),
			"FrameAttrBorderWidth":             reflect.ValueOf(q.FrameAttrBorderWidth),
			"FrameAttrHeight":                  reflect.ValueOf(q.FrameAttrHeight),
			"FrameAttrPadding":                 reflect.ValueOf(q.FrameAttrPadding),
			"FrameAttrReliefStyle":             reflect.ValueOf(q.FrameAttrReliefStyle),
			"FrameAttrTakeFocus":               reflect.ValueOf(q.FrameAttrTakeFocus),
			"FrameAttrWidth":                   reflect.ValueOf(q.FrameAttrWidth),
			"GetClipboardText":                 reflect.ValueOf(q.GetClipboardText),
			"GetOpenFile":                      reflect.ValueOf(q.GetOpenFile),
			"GetOpenMultipleFile":              reflect.ValueOf(q.GetOpenMultipleFile),
			"GetSaveFile":                      reflect.ValueOf(q.GetSaveFile),
			"GrabWidget":                       reflect.ValueOf(q.GrabWidget),
			"Grid":                             reflect.ValueOf(q.Grid),
			"GridAttrColumn":                   reflect.ValueOf(q.GridAttrColumn),
			"GridAttrColumnSpan":               reflect.ValueOf(q.GridAttrColumnSpan),
			"GridAttrInMaster":                 reflect.ValueOf(q.GridAttrInMaster),
			"GridAttrIpadx":                    reflect.ValueOf(q.GridAttrIpadx),
			"GridAttrIpady":                    reflect.ValueOf(q.GridAttrIpady),
			"GridAttrPadx":                     reflect.ValueOf(q.GridAttrPadx),
			"GridAttrPady":                     reflect.ValueOf(q.GridAttrPady),
			"GridAttrRow":                      reflect.ValueOf(q.GridAttrRow),
			"GridAttrRowSpan":                  reflect.ValueOf(q.GridAttrRowSpan),
			"GridAttrSticky":                   reflect.ValueOf(q.GridAttrSticky),
			"GridColumnIndex":                  reflect.ValueOf(q.GridColumnIndex),
			"GridIndexAttrMinSize":             reflect.ValueOf(q.GridIndexAttrMinSize),
			"GridIndexAttrPad":                 reflect.ValueOf(q.GridIndexAttrPad),
			"GridIndexAttrUniform":             reflect.ValueOf(q.GridIndexAttrUniform),
			"GridIndexAttrWeight":              reflect.ValueOf(q.GridIndexAttrWeight),
			"GridList":                         reflect.ValueOf(q.GridList),
			"GridRemove":                       reflect.ValueOf(q.GridRemove),
			"GridRowIndex":                     reflect.ValueOf(q.GridRowIndex),
			"HasTheme":                         reflect.ValueOf(q.HasTheme),
			"ImageAttrGamma":                   reflect.ValueOf(q.ImageAttrGamma),
			"ImageAttrTk85AlphaColor":          reflect.ValueOf(q.ImageAttrTk85AlphaColor),
			"Init":                             reflect.ValueOf(q.Init),
			"InitEx":                           reflect.ValueOf(q.InitEx),
			"IsEvent":                          reflect.ValueOf(q.IsEvent),
			"IsNilInterface":                   reflect.ValueOf(q.IsNilInterface),
			"IsTkClass":                        reflect.ValueOf(q.IsTkClass),
			"IsTtkClass":                       reflect.ValueOf(q.IsTtkClass),
			"IsValidWidget":                    reflect.ValueOf(q.IsValidWidget),
			"IsVirtualEvent":                   reflect.ValueOf(q.IsVirtualEvent),
			"LabelAttrAnchor":                  reflect.ValueOf(q.LabelAttrAnchor),
			"LabelAttrBackground":              reflect.ValueOf(q.LabelAttrBackground),
			"LabelAttrBorderWidth":             reflect.ValueOf(q.LabelAttrBorderWidth),
			"LabelAttrCompound":                reflect.ValueOf(q.LabelAttrCompound),
			"LabelAttrFont":                    reflect.ValueOf(q.LabelAttrFont),
			"LabelAttrForground":               reflect.ValueOf(q.LabelAttrForground),
			"LabelAttrImage":                   reflect.ValueOf(q.LabelAttrImage),
			"LabelAttrJustify":                 reflect.ValueOf(q.LabelAttrJustify),
			"LabelAttrPadding":                 reflect.ValueOf(q.LabelAttrPadding),
			"LabelAttrReliefStyle":             reflect.ValueOf(q.LabelAttrReliefStyle),
			"LabelAttrState":                   reflect.ValueOf(q.LabelAttrState),
			"LabelAttrTakeFocus":               reflect.ValueOf(q.LabelAttrTakeFocus),
			"LabelAttrText":                    reflect.ValueOf(q.LabelAttrText),
			"LabelAttrWidth":                   reflect.ValueOf(q.LabelAttrWidth),
			"LabelAttrWrapLength":              reflect.ValueOf(q.LabelAttrWrapLength),
			"LabelFrameAttrBorderWidth":        reflect.ValueOf(q.LabelFrameAttrBorderWidth),
			"LabelFrameAttrHeight":             reflect.ValueOf(q.LabelFrameAttrHeight),
			"LabelFrameAttrLabelAnchor":        reflect.ValueOf(q.LabelFrameAttrLabelAnchor),
			"LabelFrameAttrLabelText":          reflect.ValueOf(q.LabelFrameAttrLabelText),
			"LabelFrameAttrPadding":            reflect.ValueOf(q.LabelFrameAttrPadding),
			"LabelFrameAttrReliefStyle":        reflect.ValueOf(q.LabelFrameAttrReliefStyle),
			"LabelFrameAttrTakeFocus":          reflect.ValueOf(q.LabelFrameAttrTakeFocus),
			"LabelFrameAttrWidth":              reflect.ValueOf(q.LabelFrameAttrWidth),
			"ListBoxAttrBackground":            reflect.ValueOf(q.ListBoxAttrBackground),
			"ListBoxAttrBorderWidth":           reflect.ValueOf(q.ListBoxAttrBorderWidth),
			"ListBoxAttrFont":                  reflect.ValueOf(q.ListBoxAttrFont),
			"ListBoxAttrForground":             reflect.ValueOf(q.ListBoxAttrForground),
			"ListBoxAttrHeight":                reflect.ValueOf(q.ListBoxAttrHeight),
			"ListBoxAttrJustify":               reflect.ValueOf(q.ListBoxAttrJustify),
			"ListBoxAttrPadding":               reflect.ValueOf(q.ListBoxAttrPadding),
			"ListBoxAttrReliefStyle":           reflect.ValueOf(q.ListBoxAttrReliefStyle),
			"ListBoxAttrSelectMode":            reflect.ValueOf(q.ListBoxAttrSelectMode),
			"ListBoxAttrState":                 reflect.ValueOf(q.ListBoxAttrState),
			"ListBoxAttrTakeFocus":             reflect.ValueOf(q.ListBoxAttrTakeFocus),
			"ListBoxAttrWidth":                 reflect.ValueOf(q.ListBoxAttrWidth),
			"LoadImage":                        reflect.ValueOf(q.LoadImage),
			"LoadSysFont":                      reflect.ValueOf(q.LoadSysFont),
			"LookupWidget":                     reflect.ValueOf(q.LookupWidget),
			"MainInterp":                       reflect.ValueOf(q.MainInterp),
			"MainLoop":                         reflect.ValueOf(q.MainLoop),
			"MainTheme":                        reflect.ValueOf(q.MainTheme),
			"MenuAttrActiveBackground":         reflect.ValueOf(q.MenuAttrActiveBackground),
			"MenuAttrActiveBorderWidth":        reflect.ValueOf(q.MenuAttrActiveBorderWidth),
			"MenuAttrActiveForground":          reflect.ValueOf(q.MenuAttrActiveForground),
			"MenuAttrBackground":               reflect.ValueOf(q.MenuAttrBackground),
			"MenuAttrBorderWidth":              reflect.ValueOf(q.MenuAttrBorderWidth),
			"MenuAttrDisabledForground":        reflect.ValueOf(q.MenuAttrDisabledForground),
			"MenuAttrFont":                     reflect.ValueOf(q.MenuAttrFont),
			"MenuAttrForground":                reflect.ValueOf(q.MenuAttrForground),
			"MenuAttrReliefStyle":              reflect.ValueOf(q.MenuAttrReliefStyle),
			"MenuAttrSelectColor":              reflect.ValueOf(q.MenuAttrSelectColor),
			"MenuAttrTakeFocus":                reflect.ValueOf(q.MenuAttrTakeFocus),
			"MenuAttrTearoff":                  reflect.ValueOf(q.MenuAttrTearoff),
			"MenuAttrTearoffTitle":             reflect.ValueOf(q.MenuAttrTearoffTitle),
			"MenuButtonAttrCompound":           reflect.ValueOf(q.MenuButtonAttrCompound),
			"MenuButtonAttrDirection":          reflect.ValueOf(q.MenuButtonAttrDirection),
			"MenuButtonAttrImage":              reflect.ValueOf(q.MenuButtonAttrImage),
			"MenuButtonAttrMenu":               reflect.ValueOf(q.MenuButtonAttrMenu),
			"MenuButtonAttrPadding":            reflect.ValueOf(q.MenuButtonAttrPadding),
			"MenuButtonAttrState":              reflect.ValueOf(q.MenuButtonAttrState),
			"MenuButtonAttrTakeFocus":          reflect.ValueOf(q.MenuButtonAttrTakeFocus),
			"MenuButtonAttrText":               reflect.ValueOf(q.MenuButtonAttrText),
			"MenuButtonAttrWidth":              reflect.ValueOf(q.MenuButtonAttrWidth),
			"MessageBox":                       reflect.ValueOf(q.MessageBox),
			"NativeEventAttr":                  reflect.ValueOf(q.NativeEventAttr),
			"NewAction":                        reflect.ValueOf(q.NewAction),
			"NewActionEx":                      reflect.ValueOf(q.NewActionEx),
			"NewActionGroup":                   reflect.ValueOf(q.NewActionGroup),
			"NewButton":                        reflect.ValueOf(q.NewButton),
			"NewCanvas":                        reflect.ValueOf(q.NewCanvas),
			"NewCheckAction":                   reflect.ValueOf(q.NewCheckAction),
			"NewCheckActionEx":                 reflect.ValueOf(q.NewCheckActionEx),
			"NewCheckButton":                   reflect.ValueOf(q.NewCheckButton),
			"NewComboBox":                      reflect.ValueOf(q.NewComboBox),
			"NewEntry":                         reflect.ValueOf(q.NewEntry),
			"NewFrame":                         reflect.ValueOf(q.NewFrame),
			"NewGenInt64Func":                  reflect.ValueOf(q.NewGenInt64Func),
			"NewGenIntFunc":                    reflect.ValueOf(q.NewGenIntFunc),
			"NewGridLayout":                    reflect.ValueOf(q.NewGridLayout),
			"NewHPackLayout":                   reflect.ValueOf(q.NewHPackLayout),
			"NewImage":                         reflect.ValueOf(q.NewImage),
			"NewLabel":                         reflect.ValueOf(q.NewLabel),
			"NewLabelFrame":                    reflect.ValueOf(q.NewLabelFrame),
			"NewLayoutFrame":                   reflect.ValueOf(q.NewLayoutFrame),
			"NewLayoutSpacer":                  reflect.ValueOf(q.NewLayoutSpacer),
			"NewListBox":                       reflect.ValueOf(q.NewListBox),
			"NewListBoxEx":                     reflect.ValueOf(q.NewListBoxEx),
			"NewMenu":                          reflect.ValueOf(q.NewMenu),
			"NewMenuButton":                    reflect.ValueOf(q.NewMenuButton),
			"NewNamedId":                       reflect.ValueOf(q.NewNamedId),
			"NewNotebook":                      reflect.ValueOf(q.NewNotebook),
			"NewPackLayout":                    reflect.ValueOf(q.NewPackLayout),
			"NewPaned":                         reflect.ValueOf(q.NewPaned),
			"NewPlaceFrame":                    reflect.ValueOf(q.NewPlaceFrame),
			"NewProgressBar":                   reflect.ValueOf(q.NewProgressBar),
			"NewRadioAction":                   reflect.ValueOf(q.NewRadioAction),
			"NewRadioButton":                   reflect.ValueOf(q.NewRadioButton),
			"NewRadioGroup":                    reflect.ValueOf(q.NewRadioGroup),
			"NewScale":                         reflect.ValueOf(q.NewScale),
			"NewScrollBar":                     reflect.ValueOf(q.NewScrollBar),
			"NewScrollLayout":                  reflect.ValueOf(q.NewScrollLayout),
			"NewSeparator":                     reflect.ValueOf(q.NewSeparator),
			"NewSeparatorAction":               reflect.ValueOf(q.NewSeparatorAction),
			"NewSpinBox":                       reflect.ValueOf(q.NewSpinBox),
			"NewText":                          reflect.ValueOf(q.NewText),
			"NewTextEx":                        reflect.ValueOf(q.NewTextEx),
			"NewTreeView":                      reflect.ValueOf(q.NewTreeView),
			"NewTreeViewEx":                    reflect.ValueOf(q.NewTreeViewEx),
			"NewUserFont":                      reflect.ValueOf(q.NewUserFont),
			"NewUserFontFromClone":             reflect.ValueOf(q.NewUserFontFromClone),
			"NewVPackLayout":                   reflect.ValueOf(q.NewVPackLayout),
			"NewWindow":                        reflect.ValueOf(q.NewWindow),
			"NotebookAttrHeight":               reflect.ValueOf(q.NotebookAttrHeight),
			"NotebookAttrPadding":              reflect.ValueOf(q.NotebookAttrPadding),
			"NotebookAttrTakeFocus":            reflect.ValueOf(q.NotebookAttrTakeFocus),
			"NotebookAttrWidth":                reflect.ValueOf(q.NotebookAttrWidth),
			"Pack":                             reflect.ValueOf(q.Pack),
			"PackAttrAfter":                    reflect.ValueOf(q.PackAttrAfter),
			"PackAttrAnchor":                   reflect.ValueOf(q.PackAttrAnchor),
			"PackAttrBefore":                   reflect.ValueOf(q.PackAttrBefore),
			"PackAttrExpand":                   reflect.ValueOf(q.PackAttrExpand),
			"PackAttrFill":                     reflect.ValueOf(q.PackAttrFill),
			"PackAttrFillBoth":                 reflect.ValueOf(q.PackAttrFillBoth),
			"PackAttrFillNone":                 reflect.ValueOf(q.PackAttrFillNone),
			"PackAttrFillX":                    reflect.ValueOf(q.PackAttrFillX),
			"PackAttrFillY":                    reflect.ValueOf(q.PackAttrFillY),
			"PackAttrInMaster":                 reflect.ValueOf(q.PackAttrInMaster),
			"PackAttrIpadx":                    reflect.ValueOf(q.PackAttrIpadx),
			"PackAttrIpady":                    reflect.ValueOf(q.PackAttrIpady),
			"PackAttrPadx":                     reflect.ValueOf(q.PackAttrPadx),
			"PackAttrPady":                     reflect.ValueOf(q.PackAttrPady),
			"PackAttrSide":                     reflect.ValueOf(q.PackAttrSide),
			"PackAttrSideBottom":               reflect.ValueOf(q.PackAttrSideBottom),
			"PackAttrSideLeft":                 reflect.ValueOf(q.PackAttrSideLeft),
			"PackAttrSideRight":                reflect.ValueOf(q.PackAttrSideRight),
			"PackAttrSideTop":                  reflect.ValueOf(q.PackAttrSideTop),
			"PackList":                         reflect.ValueOf(q.PackList),
			"PackRemove":                       reflect.ValueOf(q.PackRemove),
			"PanedAttrHeight":                  reflect.ValueOf(q.PanedAttrHeight),
			"PanedAttrWidth":                   reflect.ValueOf(q.PanedAttrWidth),
			"ParentOfWidget":                   reflect.ValueOf(q.ParentOfWidget),
			"Place":                            reflect.ValueOf(q.Place),
			"PlaceAttrAnchor":                  reflect.ValueOf(q.PlaceAttrAnchor),
			"PlaceAttrBorderMode":              reflect.ValueOf(q.PlaceAttrBorderMode),
			"PlaceAttrHeight":                  reflect.ValueOf(q.PlaceAttrHeight),
			"PlaceAttrInMaster":                reflect.ValueOf(q.PlaceAttrInMaster),
			"PlaceAttrRelHeight":               reflect.ValueOf(q.PlaceAttrRelHeight),
			"PlaceAttrRelWidth":                reflect.ValueOf(q.PlaceAttrRelWidth),
			"PlaceAttrRelX":                    reflect.ValueOf(q.PlaceAttrRelX),
			"PlaceAttrRelY":                    reflect.ValueOf(q.PlaceAttrRelY),
			"PlaceAttrWidth":                   reflect.ValueOf(q.PlaceAttrWidth),
			"PlaceAttrX":                       reflect.ValueOf(q.PlaceAttrX),
			"PlaceAttrY":                       reflect.ValueOf(q.PlaceAttrY),
			"PlaceRemove":                      reflect.ValueOf(q.PlaceRemove),
			"PopupMenu":                        reflect.ValueOf(q.PopupMenu),
			"ProgressBarAttrLength":            reflect.ValueOf(q.ProgressBarAttrLength),
			"ProgressBarAttrMaximum":           reflect.ValueOf(q.ProgressBarAttrMaximum),
			"ProgressBarAttrOrient":            reflect.ValueOf(q.ProgressBarAttrOrient),
			"ProgressBarAttrTakeFocus":         reflect.ValueOf(q.ProgressBarAttrTakeFocus),
			"ProgressBarAttrValue":             reflect.ValueOf(q.ProgressBarAttrValue),
			"Quit":                             reflect.ValueOf(q.Quit),
			"RadioButtonAttrCompound":          reflect.ValueOf(q.RadioButtonAttrCompound),
			"RadioButtonAttrImage":             reflect.ValueOf(q.RadioButtonAttrImage),
			"RadioButtonAttrPadding":           reflect.ValueOf(q.RadioButtonAttrPadding),
			"RadioButtonAttrState":             reflect.ValueOf(q.RadioButtonAttrState),
			"RadioButtonAttrTakeFocus":         reflect.ValueOf(q.RadioButtonAttrTakeFocus),
			"RadioButtonAttrText":              reflect.ValueOf(q.RadioButtonAttrText),
			"RadioButtonAttrWidth":             reflect.ValueOf(q.RadioButtonAttrWidth),
			"RegisterWidget":                   reflect.ValueOf(q.RegisterWidget),
			"RemoveVirtualEventPhysicalEvent":  reflect.ValueOf(q.RemoveVirtualEventPhysicalEvent),
			"RootWindow":                       reflect.ValueOf(q.RootWindow),
			"ScaleAttrFrom":                    reflect.ValueOf(q.ScaleAttrFrom),
			"ScaleAttrLength":                  reflect.ValueOf(q.ScaleAttrLength),
			"ScaleAttrOrient":                  reflect.ValueOf(q.ScaleAttrOrient),
			"ScaleAttrTakeFocus":               reflect.ValueOf(q.ScaleAttrTakeFocus),
			"ScaleAttrTo":                      reflect.ValueOf(q.ScaleAttrTo),
			"ScaleAttrValue":                   reflect.ValueOf(q.ScaleAttrValue),
			"ScrollBarAttrOrient":              reflect.ValueOf(q.ScrollBarAttrOrient),
			"ScrollBarAttrTakeFocus":           reflect.ValueOf(q.ScrollBarAttrTakeFocus),
			"SendEvent":                        reflect.ValueOf(q.SendEvent),
			"SendEventToFocus":                 reflect.ValueOf(q.SendEventToFocus),
			"SeparatorAttrOrient":              reflect.ValueOf(q.SeparatorAttrOrient),
			"SeparatorAttrTakeFocus":           reflect.ValueOf(q.SeparatorAttrTakeFocus),
			"SetErrorHandle":                   reflect.ValueOf(q.SetErrorHandle),
			"SetFocusFollowsMouse":             reflect.ValueOf(q.SetFocusFollowsMouse),
			"SetMainTheme":                     reflect.ValueOf(q.SetMainTheme),
			"SetMenuTearoff":                   reflect.ValueOf(q.SetMenuTearoff),
			"SpinBoxAttrFrom":                  reflect.ValueOf(q.SpinBoxAttrFrom),
			"SpinBoxAttrIncrement":             reflect.ValueOf(q.SpinBoxAttrIncrement),
			"SpinBoxAttrTakeFocus":             reflect.ValueOf(q.SpinBoxAttrTakeFocus),
			"SpinBoxAttrTextValues":            reflect.ValueOf(q.SpinBoxAttrTextValues),
			"SpinBoxAttrTo":                    reflect.ValueOf(q.SpinBoxAttrTo),
			"SpinBoxAttrWrap":                  reflect.ValueOf(q.SpinBoxAttrWrap),
			"SubString":                        reflect.ValueOf(q.SubString),
			"TabAttrCompound":                  reflect.ValueOf(q.TabAttrCompound),
			"TabAttrImage":                     reflect.ValueOf(q.TabAttrImage),
			"TabAttrPadding":                   reflect.ValueOf(q.TabAttrPadding),
			"TabAttrState":                     reflect.ValueOf(q.TabAttrState),
			"TabAttrSticky":                    reflect.ValueOf(q.TabAttrSticky),
			"TabAttrText":                      reflect.ValueOf(q.TabAttrText),
			"TclLibary":                        reflect.ValueOf(q.TclLibary),
			"TclVersion":                       reflect.ValueOf(q.TclVersion),
			"TextAttrAutoSeparatorsOnUndo":     reflect.ValueOf(q.TextAttrAutoSeparatorsOnUndo),
			"TextAttrBackground":               reflect.ValueOf(q.TextAttrBackground),
			"TextAttrBlockCursor":              reflect.ValueOf(q.TextAttrBlockCursor),
			"TextAttrBorderWidth":              reflect.ValueOf(q.TextAttrBorderWidth),
			"TextAttrEnableUndo":               reflect.ValueOf(q.TextAttrEnableUndo),
			"TextAttrEndLine":                  reflect.ValueOf(q.TextAttrEndLine),
			"TextAttrFont":                     reflect.ValueOf(q.TextAttrFont),
			"TextAttrForeground":               reflect.ValueOf(q.TextAttrForeground),
			"TextAttrHeight":                   reflect.ValueOf(q.TextAttrHeight),
			"TextAttrHighlightBackground":      reflect.ValueOf(q.TextAttrHighlightBackground),
			"TextAttrHighlightColor":           reflect.ValueOf(q.TextAttrHighlightColor),
			"TextAttrHighlightthickness":       reflect.ValueOf(q.TextAttrHighlightthickness),
			"TextAttrInactiveSelectBackground": reflect.ValueOf(q.TextAttrInactiveSelectBackground),
			"TextAttrInsertBackground":         reflect.ValueOf(q.TextAttrInsertBackground),
			"TextAttrInsertBorderWidth":        reflect.ValueOf(q.TextAttrInsertBorderWidth),
			"TextAttrInsertOffTime":            reflect.ValueOf(q.TextAttrInsertOffTime),
			"TextAttrInsertOnTime":             reflect.ValueOf(q.TextAttrInsertOnTime),
			"TextAttrInsertUnfocussed":         reflect.ValueOf(q.TextAttrInsertUnfocussed),
			"TextAttrInsertWidth":              reflect.ValueOf(q.TextAttrInsertWidth),
			"TextAttrLineAboveSpace":           reflect.ValueOf(q.TextAttrLineAboveSpace),
			"TextAttrLineBelowSpace":           reflect.ValueOf(q.TextAttrLineBelowSpace),
			"TextAttrLineWrap":                 reflect.ValueOf(q.TextAttrLineWrap),
			"TextAttrLineWrapSpace":            reflect.ValueOf(q.TextAttrLineWrapSpace),
			"TextAttrMaxUndo":                  reflect.ValueOf(q.TextAttrMaxUndo),
			"TextAttrPadding":                  reflect.ValueOf(q.TextAttrPadding),
			"TextAttrReliefStyle":              reflect.ValueOf(q.TextAttrReliefStyle),
			"TextAttrSelectBackground":         reflect.ValueOf(q.TextAttrSelectBackground),
			"TextAttrSelectborderwidth":        reflect.ValueOf(q.TextAttrSelectborderwidth),
			"TextAttrSelectforeground":         reflect.ValueOf(q.TextAttrSelectforeground),
			"TextAttrStartLine":                reflect.ValueOf(q.TextAttrStartLine),
			"TextAttrTakeFocus":                reflect.ValueOf(q.TextAttrTakeFocus),
			"TextAttrWidth":                    reflect.ValueOf(q.TextAttrWidth),
			"TkLibrary":                        reflect.ValueOf(q.TkLibrary),
			"TkVersion":                        reflect.ValueOf(q.TkVersion),
			"TreeViewAttrHeight":               reflect.ValueOf(q.TreeViewAttrHeight),
			"TreeViewAttrPadding":              reflect.ValueOf(q.TreeViewAttrPadding),
			"TreeViewAttrTakeFocus":            reflect.ValueOf(q.TreeViewAttrTakeFocus),
			"TreeViewAttrTreeSelectMode":       reflect.ValueOf(q.TreeViewAttrTreeSelectMode),
			"Update":                           reflect.ValueOf(q.Update),
			"VirtualEventInfo":                 reflect.ValueOf(q.VirtualEventInfo),
			"WidgetAttrBorderWidth":            reflect.ValueOf(q.WidgetAttrBorderWidth),
			"WidgetAttrFont":                   reflect.ValueOf(q.WidgetAttrFont),
			"WidgetAttrHeight":                 reflect.ValueOf(q.WidgetAttrHeight),
			"WidgetAttrImage":                  reflect.ValueOf(q.WidgetAttrImage),
			"WidgetAttrInitUseTheme":           reflect.ValueOf(q.WidgetAttrInitUseTheme),
			"WidgetAttrPadding":                reflect.ValueOf(q.WidgetAttrPadding),
			"WidgetAttrPaddingN":               reflect.ValueOf(q.WidgetAttrPaddingN),
			"WidgetAttrReliefStyle":            reflect.ValueOf(q.WidgetAttrReliefStyle),
			"WidgetAttrText":                   reflect.ValueOf(q.WidgetAttrText),
			"WidgetAttrWidth":                  reflect.ValueOf(q.WidgetAttrWidth),
			"WindowOptBorderWidth":             reflect.ValueOf(q.WindowOptBorderWidth),
			"WindowOptId":                      reflect.ValueOf(q.WindowOptId),
			"WindowOptPadx":                    reflect.ValueOf(q.WindowOptPadx),
			"WindowOptPady":                    reflect.ValueOf(q.WindowOptPady),
			"WindowOptReliefStyle":             reflect.ValueOf(q.WindowOptReliefStyle),
		},
		TypedConsts: map[string]igop.TypedConst{
			"AnchorCenter":                   {reflect.TypeOf(q.AnchorCenter), constant.MakeInt64(int64(q.AnchorCenter))},
			"AnchorEast":                     {reflect.TypeOf(q.AnchorEast), constant.MakeInt64(int64(q.AnchorEast))},
			"AnchorNorth":                    {reflect.TypeOf(q.AnchorNorth), constant.MakeInt64(int64(q.AnchorNorth))},
			"AnchorNorthEast":                {reflect.TypeOf(q.AnchorNorthEast), constant.MakeInt64(int64(q.AnchorNorthEast))},
			"AnchorNorthWest":                {reflect.TypeOf(q.AnchorNorthWest), constant.MakeInt64(int64(q.AnchorNorthWest))},
			"AnchorSouth":                    {reflect.TypeOf(q.AnchorSouth), constant.MakeInt64(int64(q.AnchorSouth))},
			"AnchorSouthEast":                {reflect.TypeOf(q.AnchorSouthEast), constant.MakeInt64(int64(q.AnchorSouthEast))},
			"AnchorSouthWest":                {reflect.TypeOf(q.AnchorSouthWest), constant.MakeInt64(int64(q.AnchorSouthWest))},
			"AnchorWest":                     {reflect.TypeOf(q.AnchorWest), constant.MakeInt64(int64(q.AnchorWest))},
			"BorderModeIgnore":               {reflect.TypeOf(q.BorderModeIgnore), constant.MakeInt64(int64(q.BorderModeIgnore))},
			"BorderModeInside":               {reflect.TypeOf(q.BorderModeInside), constant.MakeInt64(int64(q.BorderModeInside))},
			"BorderModeOutside":              {reflect.TypeOf(q.BorderModeOutside), constant.MakeInt64(int64(q.BorderModeOutside))},
			"CompoundBottom":                 {reflect.TypeOf(q.CompoundBottom), constant.MakeInt64(int64(q.CompoundBottom))},
			"CompoundCenter":                 {reflect.TypeOf(q.CompoundCenter), constant.MakeInt64(int64(q.CompoundCenter))},
			"CompoundLeft":                   {reflect.TypeOf(q.CompoundLeft), constant.MakeInt64(int64(q.CompoundLeft))},
			"CompoundNone":                   {reflect.TypeOf(q.CompoundNone), constant.MakeInt64(int64(q.CompoundNone))},
			"CompoundRight":                  {reflect.TypeOf(q.CompoundRight), constant.MakeInt64(int64(q.CompoundRight))},
			"CompoundTop":                    {reflect.TypeOf(q.CompoundTop), constant.MakeInt64(int64(q.CompoundTop))},
			"DirectionAbove":                 {reflect.TypeOf(q.DirectionAbove), constant.MakeInt64(int64(q.DirectionAbove))},
			"DirectionBelow":                 {reflect.TypeOf(q.DirectionBelow), constant.MakeInt64(int64(q.DirectionBelow))},
			"DirectionLeft":                  {reflect.TypeOf(q.DirectionLeft), constant.MakeInt64(int64(q.DirectionLeft))},
			"DirectionRight":                 {reflect.TypeOf(q.DirectionRight), constant.MakeInt64(int64(q.DirectionRight))},
			"DisplyCursorHollow":             {reflect.TypeOf(q.DisplyCursorHollow), constant.MakeInt64(int64(q.DisplyCursorHollow))},
			"DisplyCursorNone":               {reflect.TypeOf(q.DisplyCursorNone), constant.MakeInt64(int64(q.DisplyCursorNone))},
			"DisplyCursorSolid":              {reflect.TypeOf(q.DisplyCursorSolid), constant.MakeInt64(int64(q.DisplyCursorSolid))},
			"FillBoth":                       {reflect.TypeOf(q.FillBoth), constant.MakeInt64(int64(q.FillBoth))},
			"FillNone":                       {reflect.TypeOf(q.FillNone), constant.MakeInt64(int64(q.FillNone))},
			"FillX":                          {reflect.TypeOf(q.FillX), constant.MakeInt64(int64(q.FillX))},
			"FillY":                          {reflect.TypeOf(q.FillY), constant.MakeInt64(int64(q.FillY))},
			"Horizontal":                     {reflect.TypeOf(q.Horizontal), constant.MakeInt64(int64(q.Horizontal))},
			"JustifyCenter":                  {reflect.TypeOf(q.JustifyCenter), constant.MakeInt64(int64(q.JustifyCenter))},
			"JustifyLeft":                    {reflect.TypeOf(q.JustifyLeft), constant.MakeInt64(int64(q.JustifyLeft))},
			"JustifyRight":                   {reflect.TypeOf(q.JustifyRight), constant.MakeInt64(int64(q.JustifyRight))},
			"KeyModifierAlt":                 {reflect.TypeOf(q.KeyModifierAlt), constant.MakeInt64(int64(q.KeyModifierAlt))},
			"KeyModifierControl":             {reflect.TypeOf(q.KeyModifierControl), constant.MakeInt64(int64(q.KeyModifierControl))},
			"KeyModifierFn":                  {reflect.TypeOf(q.KeyModifierFn), constant.MakeInt64(int64(q.KeyModifierFn))},
			"KeyModifierMeta":                {reflect.TypeOf(q.KeyModifierMeta), constant.MakeInt64(int64(q.KeyModifierMeta))},
			"KeyModifierNone":                {reflect.TypeOf(q.KeyModifierNone), constant.MakeInt64(int64(q.KeyModifierNone))},
			"KeyModifierShift":               {reflect.TypeOf(q.KeyModifierShift), constant.MakeInt64(int64(q.KeyModifierShift))},
			"LineWrapChar":                   {reflect.TypeOf(q.LineWrapChar), constant.MakeInt64(int64(q.LineWrapChar))},
			"LineWrapNone":                   {reflect.TypeOf(q.LineWrapNone), constant.MakeInt64(int64(q.LineWrapNone))},
			"LineWrapWord":                   {reflect.TypeOf(q.LineWrapWord), constant.MakeInt64(int64(q.LineWrapWord))},
			"ListSelectBrowse":               {reflect.TypeOf(q.ListSelectBrowse), constant.MakeInt64(int64(q.ListSelectBrowse))},
			"ListSelectExtended":             {reflect.TypeOf(q.ListSelectExtended), constant.MakeInt64(int64(q.ListSelectExtended))},
			"ListSelectMultiple":             {reflect.TypeOf(q.ListSelectMultiple), constant.MakeInt64(int64(q.ListSelectMultiple))},
			"ListSelectSingle":               {reflect.TypeOf(q.ListSelectSingle), constant.MakeInt64(int64(q.ListSelectSingle))},
			"MessageBoxIconError":            {reflect.TypeOf(q.MessageBoxIconError), constant.MakeInt64(int64(q.MessageBoxIconError))},
			"MessageBoxIconInfo":             {reflect.TypeOf(q.MessageBoxIconInfo), constant.MakeInt64(int64(q.MessageBoxIconInfo))},
			"MessageBoxIconNone":             {reflect.TypeOf(q.MessageBoxIconNone), constant.MakeInt64(int64(q.MessageBoxIconNone))},
			"MessageBoxIconQuestion":         {reflect.TypeOf(q.MessageBoxIconQuestion), constant.MakeInt64(int64(q.MessageBoxIconQuestion))},
			"MessageBoxIconWarning":          {reflect.TypeOf(q.MessageBoxIconWarning), constant.MakeInt64(int64(q.MessageBoxIconWarning))},
			"MessageBoxTypeAbortRetryIgnore": {reflect.TypeOf(q.MessageBoxTypeAbortRetryIgnore), constant.MakeInt64(int64(q.MessageBoxTypeAbortRetryIgnore))},
			"MessageBoxTypeOk":               {reflect.TypeOf(q.MessageBoxTypeOk), constant.MakeInt64(int64(q.MessageBoxTypeOk))},
			"MessageBoxTypeOkCancel":         {reflect.TypeOf(q.MessageBoxTypeOkCancel), constant.MakeInt64(int64(q.MessageBoxTypeOkCancel))},
			"MessageBoxTypeRetryCancel":      {reflect.TypeOf(q.MessageBoxTypeRetryCancel), constant.MakeInt64(int64(q.MessageBoxTypeRetryCancel))},
			"MessageBoxTypeYesNo":            {reflect.TypeOf(q.MessageBoxTypeYesNo), constant.MakeInt64(int64(q.MessageBoxTypeYesNo))},
			"MessageBoxTypeYesNoCancel":      {reflect.TypeOf(q.MessageBoxTypeYesNoCancel), constant.MakeInt64(int64(q.MessageBoxTypeYesNoCancel))},
			"ReliefStyleFlat":                {reflect.TypeOf(q.ReliefStyleFlat), constant.MakeInt64(int64(q.ReliefStyleFlat))},
			"ReliefStyleGroove":              {reflect.TypeOf(q.ReliefStyleGroove), constant.MakeInt64(int64(q.ReliefStyleGroove))},
			"ReliefStyleRaised":              {reflect.TypeOf(q.ReliefStyleRaised), constant.MakeInt64(int64(q.ReliefStyleRaised))},
			"ReliefStyleRidge":               {reflect.TypeOf(q.ReliefStyleRidge), constant.MakeInt64(int64(q.ReliefStyleRidge))},
			"ReliefStyleSolid":               {reflect.TypeOf(q.ReliefStyleSolid), constant.MakeInt64(int64(q.ReliefStyleSolid))},
			"ReliefStyleSunken":              {reflect.TypeOf(q.ReliefStyleSunken), constant.MakeInt64(int64(q.ReliefStyleSunken))},
			"SideBottom":                     {reflect.TypeOf(q.SideBottom), constant.MakeInt64(int64(q.SideBottom))},
			"SideLeft":                       {reflect.TypeOf(q.SideLeft), constant.MakeInt64(int64(q.SideLeft))},
			"SideRight":                      {reflect.TypeOf(q.SideRight), constant.MakeInt64(int64(q.SideRight))},
			"SideTop":                        {reflect.TypeOf(q.SideTop), constant.MakeInt64(int64(q.SideTop))},
			"StateActive":                    {reflect.TypeOf(q.StateActive), constant.MakeInt64(int64(q.StateActive))},
			"StateDisable":                   {reflect.TypeOf(q.StateDisable), constant.MakeInt64(int64(q.StateDisable))},
			"StateNormal":                    {reflect.TypeOf(q.StateNormal), constant.MakeInt64(int64(q.StateNormal))},
			"StateReadOnly":                  {reflect.TypeOf(q.StateReadOnly), constant.MakeInt64(int64(q.StateReadOnly))},
			"StickyAll":                      {reflect.TypeOf(q.StickyAll), constant.MakeInt64(int64(q.StickyAll))},
			"StickyCenter":                   {reflect.TypeOf(q.StickyCenter), constant.MakeInt64(int64(q.StickyCenter))},
			"StickyE":                        {reflect.TypeOf(q.StickyE), constant.MakeInt64(int64(q.StickyE))},
			"StickyEW":                       {reflect.TypeOf(q.StickyEW), constant.MakeInt64(int64(q.StickyEW))},
			"StickyN":                        {reflect.TypeOf(q.StickyN), constant.MakeInt64(int64(q.StickyN))},
			"StickyNS":                       {reflect.TypeOf(q.StickyNS), constant.MakeInt64(int64(q.StickyNS))},
			"StickyS":                        {reflect.TypeOf(q.StickyS), constant.MakeInt64(int64(q.StickyS))},
			"StickyW":                        {reflect.TypeOf(q.StickyW), constant.MakeInt64(int64(q.StickyW))},
			"SysCaptionFont":                 {reflect.TypeOf(q.SysCaptionFont), constant.MakeInt64(int64(q.SysCaptionFont))},
			"SysDefaultFont":                 {reflect.TypeOf(q.SysDefaultFont), constant.MakeInt64(int64(q.SysDefaultFont))},
			"SysFixedFont":                   {reflect.TypeOf(q.SysFixedFont), constant.MakeInt64(int64(q.SysFixedFont))},
			"SysHeadingFont":                 {reflect.TypeOf(q.SysHeadingFont), constant.MakeInt64(int64(q.SysHeadingFont))},
			"SysIconFont":                    {reflect.TypeOf(q.SysIconFont), constant.MakeInt64(int64(q.SysIconFont))},
			"SysMenuFont":                    {reflect.TypeOf(q.SysMenuFont), constant.MakeInt64(int64(q.SysMenuFont))},
			"SysSmallCaptionFont":            {reflect.TypeOf(q.SysSmallCaptionFont), constant.MakeInt64(int64(q.SysSmallCaptionFont))},
			"SysTextFont":                    {reflect.TypeOf(q.SysTextFont), constant.MakeInt64(int64(q.SysTextFont))},
			"SysTooltipFont":                 {reflect.TypeOf(q.SysTooltipFont), constant.MakeInt64(int64(q.SysTooltipFont))},
			"TreeSelectBrowse":               {reflect.TypeOf(q.TreeSelectBrowse), constant.MakeInt64(int64(q.TreeSelectBrowse))},
			"TreeSelectExtended":             {reflect.TypeOf(q.TreeSelectExtended), constant.MakeInt64(int64(q.TreeSelectExtended))},
			"TreeSelectNode":                 {reflect.TypeOf(q.TreeSelectNode), constant.MakeInt64(int64(q.TreeSelectNode))},
			"Vertical":                       {reflect.TypeOf(q.Vertical), constant.MakeInt64(int64(q.Vertical))},
			"WidgetTypeButton":               {reflect.TypeOf(q.WidgetTypeButton), constant.MakeInt64(int64(q.WidgetTypeButton))},
			"WidgetTypeCanvas":               {reflect.TypeOf(q.WidgetTypeCanvas), constant.MakeInt64(int64(q.WidgetTypeCanvas))},
			"WidgetTypeCheckButton":          {reflect.TypeOf(q.WidgetTypeCheckButton), constant.MakeInt64(int64(q.WidgetTypeCheckButton))},
			"WidgetTypeComboBox":             {reflect.TypeOf(q.WidgetTypeComboBox), constant.MakeInt64(int64(q.WidgetTypeComboBox))},
			"WidgetTypeEntry":                {reflect.TypeOf(q.WidgetTypeEntry), constant.MakeInt64(int64(q.WidgetTypeEntry))},
			"WidgetTypeFrame":                {reflect.TypeOf(q.WidgetTypeFrame), constant.MakeInt64(int64(q.WidgetTypeFrame))},
			"WidgetTypeLabel":                {reflect.TypeOf(q.WidgetTypeLabel), constant.MakeInt64(int64(q.WidgetTypeLabel))},
			"WidgetTypeLabelFrame":           {reflect.TypeOf(q.WidgetTypeLabelFrame), constant.MakeInt64(int64(q.WidgetTypeLabelFrame))},
			"WidgetTypeLast":                 {reflect.TypeOf(q.WidgetTypeLast), constant.MakeInt64(int64(q.WidgetTypeLast))},
			"WidgetTypeLayoutFrame":          {reflect.TypeOf(q.WidgetTypeLayoutFrame), constant.MakeInt64(int64(q.WidgetTypeLayoutFrame))},
			"WidgetTypeLayoutSpacer":         {reflect.TypeOf(q.WidgetTypeLayoutSpacer), constant.MakeInt64(int64(q.WidgetTypeLayoutSpacer))},
			"WidgetTypeListBox":              {reflect.TypeOf(q.WidgetTypeListBox), constant.MakeInt64(int64(q.WidgetTypeListBox))},
			"WidgetTypeMenu":                 {reflect.TypeOf(q.WidgetTypeMenu), constant.MakeInt64(int64(q.WidgetTypeMenu))},
			"WidgetTypeMenuButton":           {reflect.TypeOf(q.WidgetTypeMenuButton), constant.MakeInt64(int64(q.WidgetTypeMenuButton))},
			"WidgetTypeNone":                 {reflect.TypeOf(q.WidgetTypeNone), constant.MakeInt64(int64(q.WidgetTypeNone))},
			"WidgetTypeNotebook":             {reflect.TypeOf(q.WidgetTypeNotebook), constant.MakeInt64(int64(q.WidgetTypeNotebook))},
			"WidgetTypePaned":                {reflect.TypeOf(q.WidgetTypePaned), constant.MakeInt64(int64(q.WidgetTypePaned))},
			"WidgetTypeProgressBar":          {reflect.TypeOf(q.WidgetTypeProgressBar), constant.MakeInt64(int64(q.WidgetTypeProgressBar))},
			"WidgetTypeRadioButton":          {reflect.TypeOf(q.WidgetTypeRadioButton), constant.MakeInt64(int64(q.WidgetTypeRadioButton))},
			"WidgetTypeScale":                {reflect.TypeOf(q.WidgetTypeScale), constant.MakeInt64(int64(q.WidgetTypeScale))},
			"WidgetTypeScrollBar":            {reflect.TypeOf(q.WidgetTypeScrollBar), constant.MakeInt64(int64(q.WidgetTypeScrollBar))},
			"WidgetTypeSeparator":            {reflect.TypeOf(q.WidgetTypeSeparator), constant.MakeInt64(int64(q.WidgetTypeSeparator))},
			"WidgetTypeSizeGrip":             {reflect.TypeOf(q.WidgetTypeSizeGrip), constant.MakeInt64(int64(q.WidgetTypeSizeGrip))},
			"WidgetTypeSpinBox":              {reflect.TypeOf(q.WidgetTypeSpinBox), constant.MakeInt64(int64(q.WidgetTypeSpinBox))},
			"WidgetTypeText":                 {reflect.TypeOf(q.WidgetTypeText), constant.MakeInt64(int64(q.WidgetTypeText))},
			"WidgetTypeTreeView":             {reflect.TypeOf(q.WidgetTypeTreeView), constant.MakeInt64(int64(q.WidgetTypeTreeView))},
			"WidgetTypeWindow":               {reflect.TypeOf(q.WidgetTypeWindow), constant.MakeInt64(int64(q.WidgetTypeWindow))},
		},
		UntypedConsts: map[string]igop.UntypedConst{},
	})
}
